apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    load-balancer.hetzner.cloud/name: "load-balancer-1"
    load-balancer.hetzner.cloud/health-check-port: "31154"
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

